# -*- coding: utf-8 -*-
"""VN L2 education v41 — new specialty stain seed rows (no % rates)."""
from __future__ import annotations

# Soft outlook only — no numeric success percentages
_NEW_CORE: list[dict] = [
    {
        "id": "S_VN_MANGOSTEEN",
        "name": "Mangosteen",
        "name_vi": "Măng cụt",
        "name_ko": "망고스틴",
        "group_id": "G4",
        "water_spreads": True,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": False,
        "contains_dye": True,
        "urgency": "immediate",
        "tip": "Strong purple xanthone dye; alcohol blot then oxygen whites; disclose hard residual",
        "why_ko": "[왜 이 순서] 망고스틴=강한 보라 잔톤 색소(천연 염료 수준). 찬물→알코올 블롯→흰옷 산소. 완전 제거 어렵다고 고지.",
        "why_vi": "[Tại sao] Măng cụt = sắc tố tím mạnh. Lạnh → cồn → oxy trắng. Báo khó sạch hết.",
        "fresh_path_ko": "(1) 즉시 찬물. (2) 알코올 블롯. (3) 흰옷 산소 1–2시간. (4) 세탁+직사광선. 유색·실크는 전문.",
        "fresh_path_vi": "(1) Xả lạnh ngay. (2) Chấm cồn. (3) Áo trắng: oxy 1–2 giờ. (4) Giặt + nắng. Áo màu/lụa: chuyên.",
        "dried_path_ko": "마른 보라: 알코올→산소 장침지. 잔색 고지·100% 비보장.",
        "dried_path_vi": "Tím khô: cồn → oxy dài. Báo còn vết — không 100%.",
        "success_rate_ko": "즉시: 부분 개선. 마른 자국: 낮음 — 완전 제거 비보장.",
        "success_rate_vi": "Mới: cải thiện một phần. Khô: thấp — không cam kết sạch hết.",
        "refuse_when_ko": "실크·유색에 강한 표백 강제·100% 요구 → 거절/전문.",
        "refuse_when_vi": "Ép tẩy mạnh lên lụa/áo màu hoặc đòi 100% → từ chối/chuyên.",
    },
    {
        "id": "S_VN_DURIAN",
        "name": "Durian",
        "name_vi": "Sầu riêng",
        "name_ko": "두리안",
        "group_id": "G2",
        "water_spreads": False,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": True,
        "contains_dye": True,
        "urgency": "same_day",
        "tip": "Fat + sulfur odor; dish soap then baking soda then vinegar; sun dry; may need repeats",
        "why_ko": "[왜 이 순서] 두리안=지방+황 냄새. 주방세제(지방)→베이킹소다(흡착)→식초(탈취)→햇빛. 1회에 안 빠질 수 있음.",
        "why_vi": "[Tại sao] Sầu riêng = dầu + mùi lưu huỳnh. D2 → baking → giấm → nắng. Có thể cần 2–3 lần.",
        "fresh_path_ko": "(1) 주방세제 10분. (2) 베이킹소다 페이스트 30분. (3) 식초 1:4. (4) 세탁+직사광선 3–4시간.",
        "fresh_path_vi": "(1) Nước rửa chén 10 phút. (2) Baking paste 30 phút. (3) Giấm 1:4. (4) Giặt + nắng 3–4 giờ.",
        "dried_path_ko": "마른 냄새: 베이킹+식초 반복. 향수로 덮지 마세요.",
        "dried_path_vi": "Mùi khô: lặp baking+giấm. Không xịt nước hoa che.",
        "success_rate_ko": "색보다 냄새 — 반복 시 개선. 완전 무취 비보장.",
        "success_rate_vi": "Mùi nặng hơn màu — lặp thì tốt hơn. Không cam kết hết mùi.",
        "refuse_when_ko": "락스·향수로 냄새만 가리기 요구 → 거절.",
        "refuse_when_vi": "Chỉ muốn javel/nước hoa che mùi → từ chối.",
    },
    {
        "id": "S_VN_JACKFRUIT",
        "name": "Jackfruit sap",
        "name_vi": "Nhựa mít",
        "name_ko": "잭프루트·미 수액",
        "group_id": "G2",
        "water_spreads": False,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": True,
        "contains_dye": True,
        "urgency": "same_day",
        "tip": "Latex dissolves in cooking oil then dish soap; sugar rinse; oxygen whites",
        "why_ko": "[왜 이 순서] 미 수액=라텍스(물에 안 녹음). 식용유로 녹인 뒤 주방세제로 기름 제거→당분 헹굼→흰옷 산소.",
        "why_vi": "[Tại sao] Nhựa mít tan trong dầu, không tan nước. Dầu ăn → D2 → xả đường → oxy trắng.",
        "fresh_path_ko": "(1) 식용유 소량 문지르기. (2) 주방세제. (3) 찬물 헹굼. (4) 흰옷 산소. (5) 세탁.",
        "fresh_path_vi": "(1) Thoa dầu ăn. (2) Nước rửa chén. (3) Xả lạnh. (4) Oxy trắng. (5) Giặt.",
        "dried_path_ko": "굳은 수액: 식용유 장시간→세제. 물만으로 문지르지 마세요.",
        "dried_path_vi": "Nhựa khô: dầu ăn lâu → xà phòng. Không chỉ chà nước.",
        "success_rate_ko": "식용유 선행 시 양호. 물만 쓰면 잔여.",
        "success_rate_vi": "Có dầu ăn trước: tốt. Chỉ nước: dễ còn.",
        "refuse_when_ko": "아세톤 강제(원단 손상) → 거절.",
        "refuse_when_vi": "Ép acetone (hỏng vải) → từ chối.",
    },
    {
        "id": "S_VN_BANH_XEO",
        "name": "Banh xeo oil",
        "name_vi": "Dầu bánh xèo",
        "name_ko": "반쎄오·바인쎄오 기름",
        "group_id": "G2",
        "water_spreads": False,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": True,
        "contains_dye": True,
        "urgency": "same_day",
        "tip": "Starch then coconut oil then turmeric dye; compound order; sun dry",
        "why_ko": "[왜 이 순서] 반쎄오=전분+코코넛오일+강황. 전분→오일→색소 순서. 직사광선이 커큐민을 옅게.",
        "why_vi": "[Tại sao] Bánh xèo = tinh bột + dầu dừa + nghệ. Đúng thứ tự. Nắng làm nhạt curcumin.",
        "fresh_path_ko": "(1) 마른 전분 긁기·찬물. (2) 미지근으로 오일 녹인 뒤 주방세제. (3) 알코올/산소(흰옷). (4) 세탁+햇빛.",
        "fresh_path_vi": "(1) Gạt tinh bột · xả lạnh. (2) Ấm nhẹ + nước rửa chén. (3) Cồn/oxy trắng. (4) Giặt + nắng.",
        "dried_path_ko": "마른 복합: 오일→색소 반복. 순서를 바꾸지 마세요.",
        "dried_path_vi": "Khô phức: lặp dầu→màu. Không đảo thứ tự.",
        "success_rate_ko": "신선+햇빛: 개선. 마름·실내건조: 노란 잔색 가능.",
        "success_rate_vi": "Mới + nắng: tốt hơn. Khô/trong nhà: dễ còn vàng.",
        "refuse_when_ko": "실크에 산소 강제 → 거절.",
        "refuse_when_vi": "Ép oxy lên lụa → từ chối.",
    },
    {
        "id": "S_VN_DRAGON_FRUIT",
        "name": "Dragon fruit",
        "name_vi": "Thanh long",
        "name_ko": "용과·드래곤프루트",
        "group_id": "G3",
        "water_spreads": True,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": False,
        "contains_dye": True,
        "urgency": "immediate",
        "tip": "Water-soluble pink; cold rinse fast then oxygen whites",
        "why_ko": "[왜 이 순서] 용과=수용성 분홍 색소. 즉시 찬물→흰옷 산소. 열·건조 고착 주의.",
        "why_vi": "[Tại sao] Thanh long = màu hồng tan nước. Xả lạnh sớm → oxy trắng.",
        "fresh_path_ko": "(1) 즉시 찬물. (2) 잔색 시 흰옷 산소 30분. (3) 세탁.",
        "fresh_path_vi": "(1) Xả lạnh ngay. (2) Còn màu: oxy trắng 30 phút. (3) Giặt.",
        "dried_path_ko": "마른 분홍: 식초 1:4→산소(흰옷).",
        "dried_path_vi": "Hồng khô: giấm 1:4 → oxy trắng.",
        "success_rate_ko": "즉시 헹굼: 양호. 마른 후: 중간.",
        "success_rate_vi": "Xả sớm: tốt. Khô: trung bình.",
        "refuse_when_ko": "없음(일반 처리).",
        "refuse_when_vi": "Không đặc biệt.",
    },
    {
        "id": "S_VN_MANGO",
        "name": "Mango juice",
        "name_vi": "Nước xoài",
        "name_ko": "망고 주스",
        "group_id": "G3",
        "water_spreads": True,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": False,
        "contains_dye": True,
        "urgency": "immediate",
        "tip": "Sugar + carotene; cold rinse then dish soap; oxygen whites + sun",
        "why_ko": "[왜 이 순서] 망고=당+카로틴(지용성 노란 색소). 찬물→주방세제→흰옷 산소+햇빛.",
        "why_vi": "[Tại sao] Xoài = đường + carotene. Lạnh → D2 → oxy trắng + nắng.",
        "fresh_path_ko": "(1) 찬물. (2) 주방세제 10분. (3) 흰옷 산소. (4) 세탁+직사광선.",
        "fresh_path_vi": "(1) Xả lạnh. (2) Nước rửa chén 10 phút. (3) Oxy trắng. (4) Giặt + nắng.",
        "dried_path_ko": "마른 노란기: 세제→산소→햇빛.",
        "dried_path_vi": "Vàng khô: xà phòng → oxy → nắng.",
        "success_rate_ko": "신선+햇빛: 양호. 망고스틴과 구분.",
        "success_rate_vi": "Mới + nắng: tốt. Khác măng cụt.",
        "refuse_when_ko": "없음.",
        "refuse_when_vi": "Không đặc biệt.",
    },
    {
        "id": "S_VN_RAMBUTAN",
        "name": "Rambutan",
        "name_vi": "Chôm chôm",
        "name_ko": "람부탄",
        "group_id": "G3",
        "water_spreads": True,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": False,
        "contains_dye": True,
        "urgency": "same_day",
        "tip": "Mostly sugar with light dye; cold rinse then light oxygen whites",
        "why_ko": "[왜 이 순서] 람부탄=당 위주+약한 색소. 찬물→흰옷 산소 약하게.",
        "why_vi": "[Tại sao] Chôm chôm = đường + màu nhẹ. Lạnh → oxy trắng nhẹ.",
        "fresh_path_ko": "(1) 찬물. (2) 잔색 시 흰옷 산소 15분. (3) 세탁.",
        "fresh_path_vi": "(1) Xả lạnh. (2) Còn màu: oxy 15 phút. (3) Giặt.",
        "dried_path_ko": "마른 당분: 미지근 헹굼→산소.",
        "dried_path_vi": "Đường khô: xả ấm nhẹ → oxy.",
        "success_rate_ko": "양호.",
        "success_rate_vi": "Tốt.",
        "refuse_when_ko": "없음.",
        "refuse_when_vi": "Không đặc biệt.",
    },
    {
        "id": "S_VN_COCONUT_OIL",
        "name": "Coconut oil",
        "name_vi": "Dầu dừa",
        "name_ko": "코코넛 오일",
        "group_id": "G2",
        "water_spreads": False,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": True,
        "contains_dye": False,
        "urgency": "same_day",
        "tip": "Solid when cool — melt lukewarm then dish soap; no dryer while greasy",
        "why_ko": "[왜 이 순서] 코코넛오일=차가우면 고체. 미지근으로 녹인 뒤 주방세제. 미끄러운 채 건조기 금지.",
        "why_vi": "[Tại sao] Dầu dừa đông khi mát. Ấm nhẹ → D2. Cấm sấy khi còn nhờn.",
        "fresh_path_ko": "(1) 미지근(~40°C)으로 녹이기. (2) 주방세제 원액 15분. (3) 미지근 헹굼·세탁.",
        "fresh_path_vi": "(1) Ấm nhẹ ~40°C. (2) Nước rửa chén nguyên 15 phút. (3) Xả ấm · giặt.",
        "dried_path_ko": "굳은 오일: 미지근 장시간→세제 반복.",
        "dried_path_vi": "Dầu đặc: ấm lâu → lặp D2.",
        "success_rate_ko": "녹인 뒤 세제: 양호.",
        "success_rate_vi": "Sau khi làm tan + D2: tốt.",
        "refuse_when_ko": "없음.",
        "refuse_when_vi": "Không đặc biệt.",
    },
    {
        "id": "S_VN_INCENSE_ASH",
        "name": "Incense ash / soot",
        "name_vi": "Tro nhang",
        "name_ko": "향재·향 그을음",
        "group_id": "G4",
        "water_spreads": False,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": True,
        "contains_dye": True,
        "urgency": "same_day",
        "tip": "Dry brush first (wet rub drives carbon in); dish soap for oil; vinegar if odor",
        "why_ko": "[왜 이 순서] 향재=탄소+향유. 마른 채 털기→주방세제→냄새면 식초. 젖은 채 문지르면 박힘.",
        "why_vi": "[Tại sao] Tro nhang = carbon + dầu. Phủi khô → D2 → giấm nếu mùi. Ướt chà → ngấm.",
        "fresh_path_ko": "(1) 마른 채 솔/테이프. (2) 주방세제 10분. (3) 세탁. (4) 냄새면 식초 1:4.",
        "fresh_path_vi": "(1) Phủi khô / băng keo. (2) Nước rửa chén 10 phút. (3) Giặt. (4) Mùi: giấm 1:4.",
        "dried_path_ko": "박힌 그을음: 세제→알코올 블롯(테스트).",
        "dried_path_vi": "Muội ngấm: D2 → chấm cồn (test).",
        "success_rate_ko": "건식 제거 시 양호. 젖은 문지름 후: 잔여.",
        "success_rate_vi": "Phủi khô: tốt. Sau khi chà ướt: dễ còn.",
        "refuse_when_ko": "없음.",
        "refuse_when_vi": "Không đặc biệt.",
    },
    {
        "id": "S_VN_SA_TE",
        "name": "Sa te / chili oil",
        "name_vi": "Sa tế",
        "name_ko": "사테·칠리오일",
        "group_id": "G2",
        "water_spreads": False,
        "contains_protein": False,
        "contains_tannin": False,
        "contains_oil": True,
        "contains_dye": True,
        "urgency": "immediate",
        "tip": "Oil first then alcohol for chili pigment; oxygen whites; no rub",
        "why_ko": "[왜 이 순서] 사테=고추오일+색소. 주방세제(기름)→알코올(색소)→흰옷 산소. 문지르면 번짐.",
        "why_vi": "[Tại sao] Sa tế = dầu ớt + màu. D2 → cồn → oxy trắng. Không chà.",
        "fresh_path_ko": "(1) 주방세제 5분·미지근 헹굼. (2) IPA 블롯 5–10회. (3) 흰옷 산소. (4) 세탁+햇빛.",
        "fresh_path_vi": "(1) Nước rửa chén 5 phút. (2) Chấm cồn 5–10 lần. (3) Oxy trắng. (4) Giặt + nắng.",
        "dried_path_ko": "마른 빨간기: 세제→알코올 반복. 락스 금지.",
        "dried_path_vi": "Đỏ khô: lặp D2→cồn. Cấm javel.",
        "success_rate_ko": "신선: 양호. 마름: 잔색 가능.",
        "success_rate_vi": "Mới: tốt. Khô: dễ còn.",
        "refuse_when_ko": "락스 요구 → 거절.",
        "refuse_when_vi": "Đòi javel → từ chối.",
    },
    {
        "id": "S_VN_NUOC_CHAM",
        "name": "Nuoc cham dipping sauce",
        "name_vi": "Nước chấm",
        "name_ko": "느엉쩜·디핑소스",
        "group_id": "G3",
        "water_spreads": True,
        "contains_protein": True,
        "contains_tannin": True,
        "contains_oil": False,
        "contains_dye": True,
        "urgency": "immediate",
        "tip": "Fish sauce + sugar + chili; rinse sugar then enzyme vinegar alcohol if chili",
        "why_ko": "[왜 이 순서] 느엉쩜=피시소스+설탕+고추. 당분 헹굼→효소→식초(냄새)→고추면 알코올. 느억맘과 구분.",
        "why_vi": "[Tại sao] Nước chấm = nước mắm+đường+ớt. Xả đường → enzyme → giấm → cồn nếu ớt. Khác nước mắm.",
        "fresh_path_ko": "(1) 찬물로 당분. (2) 효소 30분. (3) 식초 1:4. (4) 고추 잔색이면 알코올. (5) 세탁.",
        "fresh_path_vi": "(1) Xả lạnh lấy đường. (2) Enzyme 30 phút. (3) Giấm 1:4. (4) Còn đỏ: cồn. (5) Giặt.",
        "dried_path_ko": "마른 냄새: 효소+식초 반복. 향수 덮기 금지.",
        "dried_path_vi": "Mùi khô: lặp enzyme+giấm. Không che nước hoa.",
        "success_rate_ko": "신선: 양호. 냄새 잔류 가능 — 고지.",
        "success_rate_vi": "Mới: tốt. Có thể còn mùi — báo.",
        "refuse_when_ko": "락스로 냄새만 가리기 → 거절.",
        "refuse_when_vi": "Chỉ javel che mùi → từ chối.",
    },
]

NEW_VN_STAINS_V41: list[dict] = list(_NEW_CORE)


def vn_specialty_stain_seed_rows_v41() -> list[dict]:
    return list(NEW_VN_STAINS_V41)


L1_VN_NEW = frozenset({
    "S_VN_DRAGON_FRUIT",
    "S_VN_MANGO",
    "S_VN_RAMBUTAN",
    "S_VN_COCONUT_OIL",
    "S_VN_INCENSE_ASH",
})

COMPOUND_VN_NEW = frozenset({
    "S_VN_BANH_XEO",
    "S_VN_NUOC_CHAM",
    "S_VN_SA_TE",
    "S_VN_DURIAN",
    "S_VN_JACKFRUIT",
})

ODOR_HEAVY = frozenset({
    "S_FISH_SAUCE",
    "S_SHRIMP_PASTE",
    "S_VN_DURIAN",
    "S_VN_NUOC_CHAM",
    "S_MILDEW",
})

PIGMENT_HARD = frozenset({
    "S_VN_MANGOSTEEN",
    "S_BETEL",
    "S_CURRY",
    "S_VN_BANH_XEO",
    "S_CHILI",
    "S_VN_SA_TE",
})

OIL_FIRST = frozenset({
    "S_MOTORBIKE_OIL",
    "S_VN_COCONUT_OIL",
    "S_VN_JACKFRUIT",
    "S_SUNSCREEN",
    "S_VN_BANH_XEO",
    "S_VN_SA_TE",
    "S_VN_DURIAN",
})
