# -*- coding: utf-8 -*-
"""Phase 6 remainder: L2/L3 + leftover L1 clarity fields (no % success rates)."""
from __future__ import annotations


def _st(ko: str, vi: str) -> tuple[str, str]:
    return (
        f"◆ 【먼저 확인】 {ko}",
        f"◆ 【Kiểm tra trước】 {vi}",
    )


def _out(ko: str, vi: str) -> dict[str, str]:
    return {
        "ko": f"◆ 【예상 결과】\n{ko}",
        "vi": f"◆ 【Kết quả kỳ vọng】\n{vi}",
        "en": f"◆ 【Expected result】\n{ko}",
    }


# status / tools / outlook / donts for stains still missing after v38
_ROWS: list[tuple[str, str, str, list[str], list[str], str, str, list[str], list[str]]] = [
    # sid, status_ko_body, status_vi_body, tools_ko, tools_vi, out_ko, out_vi, donts_ko, donts_vi
    (
        "S_ENGINE_OIL",
        "엔진오일·중유\n· 매니저 확인 · 완전 제거 어려움 고지\n· 흡착→세제 → 이른 열 금지",
        "Dầu động cơ\n· Hỏi quản lý · báo khó sạch hết\n· Thấm → xà phòng · cấm nhiệt sớm",
        ["흡착재·티슈", "주방세제", "효소(허용 시)"],
        ["Khăn/thấm", "Nước rửa chén", "Enzyme (nếu được)"],
        "· 부분 개선 기대\n· 열고착·오래된 오염: 잔영 가능 — 동의",
        "· Cải thiện một phần\n· Cố định nhiệt/cũ: dễ còn",
        ["미끄러운 채 건조기·다림질 하지 마세요", "물부터 부어 문지르지 마세요"],
        ["Không sấy khi còn nhờn", "Không chà nước trước"],
    ),
    (
        "S_MOTORBIKE_OIL",
        "오토바이 오일\n· 엔진오일과 유사 · 매니저 확인\n· 흡착→세제 · 냄새·잔영 고지",
        "Dầu xe máy\n· Giống dầu động cơ · hỏi quản lý\n· Thấm → xà phòng · báo mùi/vết",
        ["흡착재", "주방세제"],
        ["Khăn thấm", "Nước rửa chén"],
        "· 부분 개선\n· 오래된·열고착: 잔영 가능",
        "· Cải thiện một phần\n· Cũ/nhiệt: dễ còn",
        ["미끄러운 채 말리지 마세요"],
        ["Không sấy khi còn nhờn"],
    ),
    (
        "S_TAR",
        "타르·아스팔트\n· L3 성향 · 전문·거절 우선 검토\n· 무리한 용제·열 금지",
        "Nhựa đường/tar\n· Ưu tiên chuyên / từ chối\n· Cấm dung môi mạnh + nhiệt",
        ["매니저 확인", "흡착재"],
        ["Hỏi quản lý", "Khăn thấm"],
        "· 매장만으로 어려움 — 전문 검토\n· 무리하면 원단 손상",
        "· Khó tại cửa hàng — xem chuyên\n· Ép dễ hỏng vải",
        ["아세톤·시너를 함부로 붓지 마세요", "다리미로 녹이지 마세요"],
        ["Không đổ acetone/thinner", "Không ủi để tan"],
    ),
    (
        "S_LATERITE",
        "적토·라테라이트\n· 말려 털기 먼저 · 철·흙 성분\n· 젖은 채 문지르면 더 먹어요",
        "Đất đỏ laterite\n· Phủi khô trước\n· Chà ướt càng ngấm",
        ["솔·티슈", "찬물", "중성·세제"],
        ["Bàn chải/khăn", "Nước lạnh", "Xà phòng trung tính"],
        "· 신선·말려 털기 후: 개선\n· 오래·열고착: 잔색 가능",
        "· Mới + phủi khô: cải thiện\n· Cũ/nhiệt: dễ còn",
        ["젖은 적토를 세게 문지르지 마세요"],
        ["Không chà đất đỏ còn ướt"],
    ),
    (
        "S_RUST",
        "녹·철분\n· 매니저 확인 · 산성 녹제거는 구석 테스트\n· 실크·울·유색 신중",
        "Gỉ sắt\n· Hỏi quản lý · thử góc nếu dùng axit\n· Lụa/len/áo màu thận trọng",
        ["매니저 확인", "구석 테스트 천"],
        ["Hỏi quản lý", "Khăn thử góc"],
        "· 부분 개선 기대\n· 오래된 녹·민감 원단: 전문 검토",
        "· Cải thiện một phần\n· Gỉ cũ/vải nhạy: xem chuyên",
        ["락스로 녹을 지우려 하지 마세요", "테스트 없이 강한 산을 붓지 마세요"],
        ["Không dùng javel cho gỉ", "Không đổ axit mạnh chưa thử"],
    ),
    (
        "S_PAINT_LATEX",
        "수성 페인트\n· 마르기 전 찬물·세제 · 마른 후 어려움\n· 실크·울은 전문 검토",
        "Sơn gốc nước\n· Còn ướt: lạnh+xà phòng · khô thì khó\n· Lụa/len: xem chuyên",
        ["찬물", "주방세제", "흡착재"],
        ["Nước lạnh", "Nước rửa chén", "Khăn thấm"],
        "· 젖은 직후: 개선 기대\n· 완전 마름: 잔색·전문",
        "· Mới ướt: cải thiện\n· Khô hẳn: còn / chuyên",
        ["마른 페인트를 칼로 깊게 긁지 마세요"],
        ["Không cạo sâu sơn khô"],
    ),
    (
        "S_PAINT_OIL",
        "유성 페인트\n· L3 · 전문·거절 우선\n· 시너·아세톤 함부로 금지",
        "Sơn dầu\n· Ưu tiên chuyên / từ chối\n· Cấm thinner/acetone tùy tiện",
        ["매니저 확인"],
        ["Hỏi quản lý"],
        "· 매장 강처리 비권장 — 전문\n· 용제 사고 위험",
        "· Không khuyến khích xử mạnh tại quán\n· Rủi ro dung môi",
        ["시너·아세톤을 직접 붓지 마세요", "밀폐 공간에서 용제 쓰지 마세요"],
        ["Không đổ thinner/acetone", "Không dùng dung môi kín khí"],
    ),
    (
        "S_INK_PERMANENT",
        "유성매직·영구 잉크\n· 전문·거절 우선 · 실크·울 특히\n· 아세톤 함부로 금지",
        "Bút lông dầu / mực vĩnh cửu\n· Ưu tiên chuyên · lụa/len đặc biệt\n· Cấm acetone tùy tiện",
        ["매니저 확인", "흰 천"],
        ["Hỏi quản lý", "Khăn trắng"],
        "· 부분만 기대 · 완전 제거 어려움\n· 민감 원단: 거절·전문",
        "· Chỉ kỳ vọng một phần\n· Vải nhạy: từ chối/chuyên",
        ["아세톤을 실크·울에 쓰지 마세요", "락스로 잉크를 지우려 하지 마세요"],
        ["Không acetone lên lụa/len", "Không javel cho mực"],
    ),
    (
        "S_GLUE",
        "접착제·본드\n· 종류(수용성/순간/핫멜트) 확인\n· 무리한 용제·열 금지",
        "Keo\n· Phân loại (nước/cyano/hotmelt)\n· Cấm dung môi/nhiệt mạnh",
        ["매니저 확인", "찬물·세제(수용성)"],
        ["Hỏi quản lý", "Lạnh+xà phòng (tan nước)"],
        "· 수용성·신선: 개선\n· 순간접착·열고착: 전문",
        "· Tan nước + mới: cải thiện\n· Cyano/nhiệt: chuyên",
        ["옷에 아세톤을 흠뻑 붓지 마세요"],
        ["Không đổ đẫm acetone lên áo"],
    ),
    (
        "S_NAIL_POLISH",
        "매니큐어\n· 아세톤은 구석 테스트 · 실크·울·아세테이트 금지에 가깝\n· 환기",
        "Sơn móng\n· Acetone thử góc · tránh lụa/len/acetate\n· Thông gió",
        ["흰 천", "환기", "매니저 확인"],
        ["Khăn trắng", "Thông gió", "Hỏi quản lý"],
        "· 면·신선: 부분 개선\n· 실크·울: 거절·전문 우선",
        "· Cotton mới: một phần\n· Lụa/len: từ chối/chuyên",
        ["실크·울·아세테이트에 아세톤 쓰지 마세요", "밀폐 공간에서 아세톤 쓰지 마세요"],
        ["Không acetone lên lụa/len/acetate", "Không dùng acetone kín khí"],
    ),
    (
        "S_SHOE_POLISH",
        "구두약\n· 왁스·색소 · 문지르면 번짐\n· 실크·울 신중",
        "Xi đánh giày\n· Sáp+màu · chà dễ loang\n· Lụa/len thận trọng",
        ["티슈", "주방세제", "흰 천"],
        ["Khăn giấy", "Nước rửa chén", "Khăn trắng"],
        "· 겉 왁스: 개선\n· 색소 먹음: 잔색 가능",
        "· Sáp ngoài: cải thiện\n· Màu ngấm: dễ còn",
        ["옆으로 세게 문지르지 마세요"],
        ["Không chà ngang mạnh"],
    ),
    (
        "S_FECES",
        "분변·토사물 오염\n· PPE · 위생 · 찬물·효소\n· 온수 먼저 금지",
        "Phân/chất bẩn\n· PPE · vệ sinh · lạnh+enzyme\n· Cấm nóng trước",
        ["장갑", "찬물", "효소세제"],
        ["Găng", "Nước lạnh", "Enzyme"],
        "· 신선·찬물: 개선\n· 열고착: 잔취·잔색 가능",
        "· Mới + lạnh: cải thiện\n· Nhiệt: dễ còn mùi/vết",
        ["온수 먼저 쓰지 마세요", "PPE 없이 맨손으로 다루지 마세요"],
        ["Không dùng nóng trước", "Không xử lý không PPE"],
    ),
    (
        "S_CURRY",
        "카레·강황\n· 지방 먼저(세제) → 색소\n· 유색·실크 산소 신중",
        "Cà ri / nghệ\n· Mỡ trước (xà phòng) → màu\n· Áo màu/lụa: oxy thận trọng",
        ["주방세제", "베이킹소다", "산소(흰옷)"],
        ["Nước rửa chén", "Baking soda", "Oxy (áo trắng)"],
        "· 신선: 개선\n· 강황 색소·열고착: 잔색 가능",
        "· Mới: cải thiện\n· Nghệ/nhiệt: dễ còn",
        ["유색·실크에 산소 함부로 쓰지 마세요"],
        ["Không oxy tùy tiện lên màu/lụa"],
    ),
    (
        "S_MUSTARD",
        "머스터드\n· 고형 제거 → 세제·효소\n· 노란 색소 잔색 고지",
        "Mù tạt\n· Gạt rắn → xà phòng/enzyme\n· Báo còn vàng",
        ["티슈", "주방세제", "효소"],
        ["Khăn", "Nước rửa chén", "Enzyme"],
        "· 신선: 개선\n· 노란 잔색 가능 — 동의",
        "· Mới: cải thiện\n· Dễ còn vàng — đồng ý",
        ["문질러 노란 색을 번지게 하지 마세요"],
        ["Không chà làm loang vàng"],
    ),
    (
        "S_SHIRT_YELLOW",
        "와이셔츠·흰옷 황변\n· 락스 금지 · 효소→산소\n· 완전 하얗게 보장 금지",
        "Áo sơ mi vàng\n· Cấm javel · enzyme→oxy\n· Không cam kết trắng 100%",
        ["효소세제", "산소표백제(허용 시)"],
        ["Enzyme", "Oxy (nếu được)"],
        "· 부분 개선 기대\n· 오래된 황변: 잔영 가능",
        "· Cải thiện một phần\n· Vàng cũ: dễ còn",
        ["황변에 락스 쓰지 마세요"],
        ["Không javel cho ố vàng"],
    ),
    (
        "S_URINE",
        "소변\n· 찬물·효소 · 온수 먼저 금지\n· 냄새 잔존 고지",
        "Nước tiểu\n· Lạnh+enzyme · cấm nóng trước\n· Báo còn mùi",
        ["찬물", "효소세제"],
        ["Nước lạnh", "Enzyme"],
        "· 신선: 개선\n· 마름·열고착: 잔취 가능",
        "· Mới: cải thiện\n· Khô/nhiệt: dễ còn mùi",
        ["온수 먼저 쓰지 마세요"],
        ["Không dùng nóng trước"],
    ),
    (
        "S_VOMIT",
        "구토물\n· PPE · 고형 제거 → 찬물·효소\n· 온수 먼저 금지",
        "Nôn\n· PPE · gạt rắn → lạnh+enzyme\n· Cấm nóng trước",
        ["장갑", "찬물", "효소"],
        ["Găng", "Nước lạnh", "Enzyme"],
        "· 신선: 개선\n· 잔취 가능 — 고지",
        "· Mới: cải thiện\n· Dễ còn mùi",
        ["온수 먼저 쓰지 마세요", "맨손으로 다루지 마세요"],
        ["Không nóng trước", "Không xử không găng"],
    ),
    (
        "S_DEODORANT",
        "땀억제제·데오 자국\n· 황변과 구분 · 알루미늄 잔여 가능\n· 락스 금지",
        "Khử mùi / deodorant\n· Khác ố vàng · có thể còn Al\n· Cấm javel",
        ["효소", "중성세제"],
        ["Enzyme", "Xà phòng trung tính"],
        "· 부분 개선\n· 오래된 흰 자국: 잔영 가능",
        "· Cải thiện một phần\n· Vết trắng cũ: dễ còn",
        ["락스로 데오 자국을 지우려 하지 마세요"],
        ["Không javel cho vết deodorant"],
    ),
    (
        "S_PERFUME",
        "향수\n· 알코올·오일 · 얼룩·변색 가능\n· 실크 신중 · 환기",
        "Nước hoa\n· Cồn+dầu · có thể ố/phai\n· Lụa thận trọng · thông gió",
        ["흰 천", "중성세제"],
        ["Khăn trắng", "Xà phòng trung tính"],
        "· 신선: 개선\n· 변색·실크: 잔색·손상 주의",
        "· Mới: cải thiện\n· Phai/lụa: rủi ro",
        ["실크에 강한 알코올을 함부로 쓰지 마세요"],
        ["Không cồn mạnh tùy tiện lên lụa"],
    ),
    (
        "S_SUNSCREEN",
        "선크림\n· 오일·실리콘 → 세제 먼저\n· 미끄러움 남으면 말리지 마세요",
        "Kem chống nắng\n· Dầu/silicon → xà phòng trước\n· Còn nhờn → không sấy",
        ["주방세제", "찬물"],
        ["Nước rửa chén", "Nước lạnh"],
        "· 겉 오일: 잘 빠지는 편\n· 열고착: 잔영 가능",
        "· Dầu ngoài: thường tốt\n· Nhiệt: dễ còn",
        ["미끄러운 채 건조기 쓰지 마세요"],
        ["Không sấy khi còn nhờn"],
    ),
    (
        "S_MILDEW",
        "곰팡이\n· 야외·환기·PPE · 가죽/실크는 전문\n· 식초+락스 동시 혼합 금지(유독가스)",
        "Nấm mốc\n· Ngoài trời·PPE · da/lụa: chuyên\n· Cấm trộn giấm+javel",
        ["장갑·마스크", "식초 1:4", "산소(흰옷)"],
        ["Găng/khẩu trang", "Giấm 1:4", "Oxy (trắng)"],
        "· 초기·면: 개선\n· 가죽·심함: 전문",
        "· Sớm + cotton: cải thiện\n· Da/nặng: chuyên",
        ["식초와 락스를 섞지 마세요", "실내에서 포자 털지 마세요"],
        ["Không trộn giấm với javel", "Không phủi bào tử trong nhà"],
    ),
    (
        "S_GUM",
        "껌\n· 차갑게 굳혀 걷어내기 · 문지름 금지\n· 잔여 지방은 세제",
        "Kẹo cao su\n· Làm cứng lạnh rồi gạt · không chà\n· Dầu còn → xà phòng",
        ["얼음·냉장", "티슈", "주방세제"],
        ["Đá/lạnh", "Khăn", "Nước rửa chén"],
        "· 굳혀 제거 후: 잘 빠지는 편\n· 섬유 속: 잔여 가능",
        "· Sau gạt cứng: thường tốt\n· Ngấm sợi: dễ còn",
        ["따뜻한 물로 먼저 녹여 문지르지 마세요"],
        ["Không làm tan nóng rồi chà"],
    ),
    (
        "S_CANDLE_WAX",
        "양초 왁스\n· 굳혀 긁기 → 흡착 · 다리미로 녹여 밀어넣지 마세요",
        "Sáp nến\n· Cứng rồi gạt → thấm · không ủi đẩy vào sợi",
        ["티슈", "흡착재", "주방세제"],
        ["Khăn", "Thấm", "Nước rửa chén"],
        "· 겉 왁스: 개선\n· 색소 양초: 잔색 가능",
        "· Sáp ngoài: cải thiện\n· Nến màu: dễ còn",
        ["다리미로 왁스를 옷 안으로 밀어넣지 마세요"],
        ["Không ủi đẩy sáp vào áo"],
    ),
    (
        "S_GREASE",
        "그리스·중유\n· 흡착→세제 · 엔진오일과 유사\n· 열고착 고지",
        "Mỡ bò / grease\n· Thấm → xà phòng\n· Báo cố định nhiệt",
        ["흡착재", "주방세제"],
        ["Khăn thấm", "Nước rửa chén"],
        "· 부분 개선\n· 열고착: 잔영 가능",
        "· Cải thiện một phần\n· Nhiệt: dễ còn",
        ["미끄러운 채 말리지 마세요"],
        ["Không sấy khi còn nhờn"],
    ),
    (
        "S_CHILI",
        "고추·고춧가루\n· 건더기 제거 → 세제·식초\n· 유색 산소 신중 · 치약 금지",
        "Ớt\n· Gạt rắn → xà phòng/giấm\n· Oxy màu thận trọng · cấm kem đánh răng",
        ["티슈", "주방세제", "식초 1:4"],
        ["Khăn", "Nước rửa chén", "Giấm 1:4"],
        "· 신선: 개선\n· 고추 색소: 잔색·자극 가능",
        "· Mới: cải thiện\n· Màu ớt: dễ còn",
        ["치약으로 지우지 마세요", "문질러 번지게 하지 마세요"],
        ["Không dùng kem đánh răng", "Không chà loang"],
    ),
    (
        "S_BETEL",
        "빈랑·부어\n· 색소 셈 · 매니저 확인\n· 실크·울 전문 검토",
        "Trầu cau\n· Màu mạnh · hỏi quản lý\n· Lụa/len: chuyên",
        ["흰 천", "식초·중성", "매니저 확인"],
        ["Khăn trắng", "Giấm/trung tính", "Hỏi quản lý"],
        "· 부분 개선\n· 마름·실크: 잔색·전문",
        "· Một phần\n· Khô/lụa: còn / chuyên",
        ["실크에 강한 표백을 쓰지 마세요"],
        ["Không tẩy mạnh lên lụa"],
    ),
    (
        "S_SHRIMP_PASTE",
        "새우젓·맘\n· 냄새·염 · 효소→식초\n· 온수·건조기 먼저 금지",
        "Mắm tôm\n· Mùi+muối · enzyme→giấm\n· Cấm nóng/sấy trước",
        ["효소", "식초", "찬물"],
        ["Enzyme", "Giấm", "Nước lạnh"],
        "· 신선: 개선\n· 냄새 잔존 가능 — 고지",
        "· Mới: cải thiện\n· Dễ còn mùi",
        ["온수 먼저 쓰지 마세요", "냄새 보장을 하지 마세요"],
        ["Không nóng trước", "Không cam kết hết mùi"],
    ),
    (
        "S_GAC",
        "깍(가크) 색소\n· 강한 주황 색소 · 매니저 확인\n· 유색·실크 신중",
        "Gấc\n· Màu cam mạnh · hỏi quản lý\n· Áo màu/lụa thận trọng",
        ["찬물", "식초 1:4", "산소(흰옷)"],
        ["Nước lạnh", "Giấm 1:4", "Oxy (trắng)"],
        "· 흰·신선: 개선\n· 유색·마름: 잔색 가능",
        "· Trắng mới: cải thiện\n· Màu/khô: dễ còn",
        ["유색에 산소 함부로 쓰지 마세요"],
        ["Không oxy tùy tiện lên áo màu"],
    ),
    (
        "S_ANNATTO",
        "아나토·주황 색소\n· 식용색소 계열 · 식초·흰옷 산소\n· 유색 신중",
        "Annatto\n· Màu thực phẩm · giấm / oxy trắng\n· Áo màu thận trọng",
        ["식초 1:4", "산소(흰옷)"],
        ["Giấm 1:4", "Oxy (trắng)"],
        "· 흰·신선: 개선\n· 열고착: 잔색 가능",
        "· Trắng mới: cải thiện\n· Nhiệt: dễ còn",
        ["유색·실크에 산소 함부로 쓰지 마세요"],
        ["Không oxy tùy tiện lên màu/lụa"],
    ),
    (
        "S_STARCH_TRANSFER",
        "전분 이염\n· 풀물·전분 이염과 일반 풀(잔디) 구분\n· 찬물·효소 중심",
        "Lem tinh bột\n· Phân biệt với cỏ\n· Lạnh+enzyme",
        ["찬물", "효소"],
        ["Nước lạnh", "Enzyme"],
        "· 신선: 개선\n· 열고착: 잔영 가능",
        "· Mới: cải thiện\n· Nhiệt: dễ còn",
        ["뜨거운 물로 전분을 먼저 굳히지 마세요"],
        ["Không dùng nóng làm cứng tinh bột"],
    ),
    (
        "S_SUGARCANE",
        "사탕수수·당분\n· 끈적 헹구기 · 남은 채 말리면 황변\n· 세제·찬물",
        "Mía / đường\n· Xả dính · để khô dễ ố vàng\n· Xà phòng+lạnh",
        ["찬물", "중성·세제"],
        ["Nước lạnh", "Xà phòng"],
        "· 신선: 잘 빠지는 편\n· 당분 남김: 황변 위험",
        "· Mới: thường tốt\n· Còn đường: rủi ố vàng",
        ["끈적 남은 채 말리지 마세요"],
        ["Không sấy khi còn dính đường"],
    ),
    (
        "S_DOENJANG",
        "된장\n· 단백질·색소 · 효소→식초\n· 온수 먼저 금지",
        "Tương đậu (doenjang)\n· Đạm+màu · enzyme→giấm\n· Cấm nóng trước",
        ["효소", "식초 1:4"],
        ["Enzyme", "Giấm 1:4"],
        "· 신선: 개선\n· 마름: 잔색·냄새 가능",
        "· Mới: cải thiện\n· Khô: dễ còn màu/mùi",
        ["온수 먼저 쓰지 마세요"],
        ["Không dùng nóng trước"],
    ),
    (
        "S_GOCHUJANG",
        "고추장\n· 고형→세제→식초 · 치약 금지\n· 유색 산소 신중",
        "Tương ớt\n· Gạt → xà phòng → giấm · cấm kem đánh răng\n· Oxy màu thận trọng",
        ["티슈", "주방세제", "식초"],
        ["Khăn", "Nước rửa chén", "Giấm"],
        "· 신선: 개선\n· 고추 색소: 잔색 가능",
        "· Mới: cải thiện\n· Màu ớt: dễ còn",
        ["치약으로 지우지 마세요"],
        ["Không dùng kem đánh răng"],
    ),
    (
        "S_PERSIMMON",
        "감·탄닌\n· 찬물·식초 · 이른 열 금지\n· 유색·실크 산소 신중",
        "Hồng / tannin\n· Lạnh+giấm · cấm nhiệt sớm\n· Oxy màu/lụa thận trọng",
        ["찬물", "식초 1:4"],
        ["Nước lạnh", "Giấm 1:4"],
        "· 신선: 개선\n· 마름·열: 잔색 가능",
        "· Mới: cải thiện\n· Khô/nhiệt: dễ còn",
        ["이른 열로 탄닌을 고착시키지 마세요"],
        ["Không cố định tannin bằng nhiệt sớm"],
    ),
    (
        "S_CRAYON",
        "크레용\n· 왁스 굳혀 걷어내기 → 세제\n· 색소 잔색 가능",
        "Bút sáp màu\n· Cứng rồi gạt → xà phòng\n· Dễ còn màu",
        ["티슈", "주방세제"],
        ["Khăn", "Nước rửa chén"],
        "· 겉 왁스: 개선\n· 색소: 잔색 가능",
        "· Sáp ngoài: cải thiện\n· Màu: dễ còn",
        ["다리미로 녹여 밀어넣지 마세요"],
        ["Không ủi đẩy sáp vào áo"],
    ),
    (
        "S_SOFTENER_SPOT",
        "유연제 얼룩\n· 과다 투입·직접 도포 흔적\n· 재세탁·헹굼 중심 · 표백 과다 금지",
        "Vết nước xả vải\n· Do đổ nhiều / đổ trực tiếp\n· Giặt lại · không tẩy quá",
        ["재세탁", "중성세제"],
        ["Giặt lại", "Xà phòng trung tính"],
        "· 재헹굼·재세탁으로 개선되는 편\n· 열고착 유분: 잔영 가능",
        "· Giặt lại thường cải thiện\n· Dầu cố định nhiệt: dễ còn",
        ["유연제 얼룩에 락스를 붓지 마세요"],
        ["Không đổ javel lên vết softener"],
    ),
    # leftover L1/L2 outlook/tools/donts only (status often already present)
    (
        "S_BLOOD_FRESH",
        "신선 피\n· 찬물만 · 온수 금지\n· 단백질 고착 주의",
        "Máu tươi\n· Chỉ lạnh · cấm nóng\n· Đạm dễ cố định",
        ["찬물", "효소세제", "장갑"],
        ["Nước lạnh", "Enzyme", "Găng"],
        "· 즉시 찬물: 잘 빠지는 편\n· 열 지남: 고착 — 부분만",
        "· Lạnh ngay: thường tốt\n· Đã nóng: chỉ một phần",
        ["뜨거운 물로 피를 헹구지 마세요"],
        ["Không xả máu bằng nước nóng"],
    ),
    (
        "S_BLOOD_DRY",
        "마른 피\n· 완전 제거 어려움 고지\n· 찬물·효소 · 온수 금지",
        "Máu khô\n· Báo khó sạch hết\n· Lạnh+enzyme · cấm nóng",
        ["찬물", "효소", "과산화수소(흰 면만)"],
        ["Nước lạnh", "Enzyme", "H2O2 (cotton trắng)"],
        "· 부분 제거 기대\n· 갈색 잔영 가능 — 동의",
        "· Kỳ vọng một phần\n· Dễ còn nâu — đồng ý",
        ["뜨거운 물로 피를 헹구지 마세요"],
        ["Không xả máu bằng nước nóng"],
    ),
    (
        "S_DYE_TRANSFER",
        "이염\n· 즉시 분리 · 건조기 금지\n· 락스는 흰 100%만·매니저",
        "Lem màu\n· Tách ngay · cấm sấy\n· Javel chỉ trắng 100% + quản lý",
        ["찬물", "매니저 확인"],
        ["Nước lạnh", "Hỏi quản lý"],
        "· 즉시 조치: 개선 가능\n· 건조기 지남: 매우 어려움",
        "· Xử ngay: có thể cải thiện\n· Đã sấy: rất khó",
        ["건조기·다림질로 이염을 고착시키지 마세요"],
        ["Không sấy/ủi cố định lem màu"],
    ),
    (
        "S_TEA",
        "차(탄닌)\n· 젖음→식초 1:4 · 마름→잔색 고지",
        "Trà (tannin)\n· Ướt→giấm 1:4 · khô→báo còn",
        ["흰 식초", "분무기", "찬물"],
        ["Giấm trắng", "Bình xịt", "Nước lạnh"],
        "· 신선: 개선\n· 마름·열: 잔색 가능",
        "· Mới: cải thiện\n· Khô/nhiệt: dễ còn",
        ["이른 열로 탄닌을 고착시키지 마세요"],
        ["Không cố định tannin bằng nhiệt sớm"],
    ),
    (
        "S_FRUIT_JUICE",
        "과일주스\n· 찬물·식초 · 당분 남김 황변",
        "Nước ép trái cây\n· Lạnh+giấm · đường còn dễ ố",
        ["찬물", "식초 1:4"],
        ["Nước lạnh", "Giấm 1:4"],
        "· 신선: 개선\n· 당분·열: 황변·잔색 가능",
        "· Mới: cải thiện\n· Đường/nhiệt: dễ ố",
        ["당분 남은 채 말리지 마세요"],
        ["Không sấy khi còn đường"],
    ),
    (
        "S_SOFT_DRINK",
        "탄산·청량음료\n· 끈적 헹구기 · 색소면 식초",
        "Nước ngọt\n· Xả dính · màu → giấm",
        ["찬물", "식초 1:4"],
        ["Nước lạnh", "Giấm 1:4"],
        "· 신선: 잘 빠지는 편\n· 당분 남김: 황변",
        "· Mới: thường tốt\n· Còn đường: ố vàng",
        ["끈적 남은 채 말리지 마세요"],
        ["Không sấy khi còn dính"],
    ),
    (
        "S_MUD",
        "흙·진흙\n· 말려 털기 먼저 · 적토면 라테라이트",
        "Bùn đất\n· Phủi khô trước · đất đỏ → laterite",
        ["솔", "찬물", "세제"],
        ["Bàn chải", "Nước lạnh", "Xà phòng"],
        "· 말려 털기 후: 잘 빠지는 편\n· 적토: 더 어려움",
        "· Sau phủi khô: thường tốt\n· Đất đỏ: khó hơn",
        ["젖은 흙을 세게 문지르지 마세요"],
        ["Không chà bùn còn ướt"],
    ),
    (
        "S_IODINE",
        "요오드·포비돈\n· 매니저 · 알코올 테스트 · 환기",
        "I-ốt / povidone\n· Quản lý · thử cồn · thông gió",
        ["이소프로필 알코올 70%", "흰 천", "환기"],
        ["Cồn IPA 70%", "Khăn trắng", "Thông gió"],
        "· 면·신선: 개선\n· 실크·마름: 전문 검토",
        "· Cotton mới: cải thiện\n· Lụa/khô: chuyên",
        ["실크·울에 알코올을 함부로 쓰지 마세요", "환기 없이 알코올 쓰지 마세요"],
        ["Không cồn tùy tiện lên lụa/len", "Không dùng cồn kín khí"],
    ),
    (
        "S_BLACK_COFFEE",
        "블랙커피\n· 탄닌 · 찬물·식초 · 열고착 고지",
        "Cà phê đen\n· Tannin · lạnh+giấm · báo nhiệt",
        ["흰 식초", "분무기", "찬물"],
        ["Giấm trắng", "Bình xịt", "Nước lạnh"],
        "· 묻은 직후: 잘 빠지는 편\n· 마름·열: 잔색 가능",
        "· Mới: thường tốt\n· Khô/nhiệt: dễ còn",
        ["잔색 채 건조기 돌리지 마세요"],
        ["Không sấy khi còn vết"],
    ),
    (
        "S_SWEAT_FRESH",
        "신선 땀\n· 효소·세탁 · 이미 노랗면 황변 요령",
        "Mồ hôi mới\n· Enzyme+giặt · đã vàng → SOP vàng",
        ["효소세제", "찬물~미온"],
        ["Enzyme", "Lạnh~ấm nhẹ"],
        "· 신선: 잘 빠지는 편\n· 황변 전이: 부분만",
        "· Mới: thường tốt\n· Chuyển vàng: chỉ một phần",
        ["황변에 락스 쓰지 마세요"],
        ["Không javel cho ố vàng"],
    ),
    (
        "S_SOY_SAUCE",
        "간장\n· 즉시 흡수 · 이른 열 금지",
        "Nước tương\n· Thấm ngay · cấm nhiệt sớm",
        ["찬물", "식초 1:4", "효소"],
        ["Nước lạnh", "Giấm 1:4", "Enzyme"],
        "· 신선: 개선\n· 마름·열: 검정 잔영 가능",
        "· Mới: cải thiện\n· Khô/nhiệt: dễ còn đen",
        ["이른 열로 색소를 고착시키지 마세요"],
        ["Không cố định màu bằng nhiệt sớm"],
    ),
    (
        "S_CHOCOLATE",
        "초콜릿\n· 긁기→지방(세제)→색소",
        "Sô-cô-la\n· Gạt → mỡ (xà phòng) → màu",
        ["티슈", "주방세제", "효소"],
        ["Khăn", "Nước rửa chén", "Enzyme"],
        "· 신선: 개선\n· 지방·색소 남김: 잔영 가능",
        "· Mới: cải thiện\n· Còn mỡ/màu: dễ còn",
        ["지방·색소 남은 채 말리지 마세요"],
        ["Không sấy khi còn mỡ/màu"],
    ),
    (
        "S_TOMATO_SAUCE",
        "토마토소스\n· 고형→세제→식초",
        "Sốt cà\n· Gạt → xà phòng → giấm",
        ["티슈", "주방세제", "식초"],
        ["Khăn", "Nước rửa chén", "Giấm"],
        "· 신선: 개선\n· 붉은 잔색 가능",
        "· Mới: cải thiện\n· Dễ còn đỏ",
        ["문질러 번지게 하지 마세요"],
        ["Không chà loang"],
    ),
    (
        "S_WHITE_WINE_BEER",
        "화이트와인·맥주\n· 당분 황변 고지 · 세제→흰옷 산소",
        "Vang trắng/bia\n· Báo ố vàng đường · xà phòng→oxy trắng",
        ["흡착 천", "중성세제", "산소(흰옷)"],
        ["Khăn thấm", "Xà phòng", "Oxy (trắng)"],
        "· 즉시 처리: 개선\n· 당분 남김: 나중에 누럴 수 있음",
        "· Xử ngay: cải thiện\n· Còn đường: sau có thể vàng",
        ["당분 남은 채 말리지 마세요"],
        ["Không sấy khi còn đường"],
    ),
    (
        "S_BUBBLE_TEA",
        "버블티\n· 지방→단백질→차 색소 순서",
        "Trà sữa trân châu\n· Mỡ → đạm → tannin",
        ["주방세제", "효소", "식초"],
        ["Nước rửa chén", "Enzyme", "Giấm"],
        "· 순서 지키면 개선\n· 순서 위반·열: 잔색 가능",
        "· Đúng thứ tự: cải thiện\n· Sai thứ tự/nhiệt: dễ còn",
        ["식초를 지방·단백질보다 먼저 쓰지 마세요"],
        ["Không giấm trước mỡ/đạm"],
    ),
    (
        "S_BBQ_SAUCE",
        "BBQ소스\n· 효소→세제→식초",
        "Sốt BBQ\n· Enzyme → xà phòng → giấm",
        ["효소", "주방세제", "식초"],
        ["Enzyme", "Nước rửa chén", "Giấm"],
        "· 신선: 개선\n· 색소·열고착: 잔색 가능",
        "· Mới: cải thiện\n· Màu/nhiệt: dễ còn",
        ["순서를 바꾸지 마세요"],
        ["Không đổi thứ tự"],
    ),
    (
        "S_MAYO",
        "마요네즈\n· 지방 먼저 → 효소",
        "Mayonnaise\n· Mỡ trước → enzyme",
        ["주방세제", "효소"],
        ["Nước rửa chén", "Enzyme"],
        "· 신선: 잘 빠지는 편\n· 온수 먼저: 고착",
        "· Mới: thường tốt\n· Nóng trước: cố định",
        ["온수 먼저 쓰지 마세요"],
        ["Không dùng nóng trước"],
    ),
    (
        "S_BUTTER",
        "버터\n· 흡착→세제 · 미끄러움 남으면 말리지 마세요",
        "Bơ\n· Thấm → xà phòng · còn nhờn không sấy",
        ["티슈", "주방세제"],
        ["Khăn", "Nước rửa chén"],
        "· 신선: 개선\n· 열고착: 잔영 가능",
        "· Mới: cải thiện\n· Nhiệt: dễ còn",
        ["미끄러운 채 말리지 마세요"],
        ["Không sấy khi còn nhờn"],
    ),
    (
        "S_FISH_SAUCE",
        "느억맘·액젓\n· 방금 묻음/마름 확인 · 효소계 세제→식초(냄새 줄이기)\n· 온수·건조기 먼저 금지 · 냄새 보장 금지",
        "Nước mắm\n· Mới/khô · enzyme→giấm (giảm mùi)\n· Cấm nóng/sấy trước · không cam kết hết mùi",
        ["효소계 세제(프로테아제)", "흰 식초(냄새 중화·줄이기)", "찬물", "담금통"],
        ["Nước giặt enzyme", "Giấm (giảm mùi)", "Nước lạnh", "Chậu"],
        "· 방금 묻은 직후: 색·냄새가 나아질 수 있음\n· 마름·열: 냄새 남을 수 있음 — 동의",
        "· Mới dính: màu/mùi có thể đỡ\n· Khô/nhiệt: dễ còn mùi — đồng ý",
        ["냄새 완전 제거를 보장하지 마세요", "온수·건조기를 먼저 쓰지 마세요"],
        ["Không cam kết hết mùi", "Không dùng nóng/sấy trước"],
    ),
    (
        "S_BABY_FORMULA",
        "분유\n· 락스 금지 · 찬물·효소",
        "Sữa bột\n· Cấm javel · lạnh+enzyme",
        ["효소", "찬물"],
        ["Enzyme", "Nước lạnh"],
        "· 신선: 개선\n· 락스·온수 먼저: 악화",
        "· Mới: cải thiện\n· Javel/nóng trước: tệ hơn",
        ["락스 절대 쓰지 마세요"],
        ["Tuyệt đối không javel"],
    ),
    (
        "S_COLLAR_STAIN",
        "목때\n· 락스 금지 · 효소 국소",
        "Cổ áo\n· Cấm javel · enzyme cục bộ",
        ["효소", "연질 솔"],
        ["Enzyme", "Bàn chải mềm"],
        "· 부분 개선\n· 오래된 목때: 잔영 가능",
        "· Cải thiện một phần\n· Cổ cũ: dễ còn",
        ["목 때에 락스 쓰지 마세요"],
        ["Không javel cổ áo"],
    ),
    (
        "S_MILK_COFFEE",
        "라떼·우유커피\n· 단백질·지방 먼저 → 식초",
        "Cà phê sữa\n· Đạm/mỡ trước → giấm",
        ["효소", "주방세제", "식초"],
        ["Enzyme", "Nước rửa chén", "Giấm"],
        "· 순서 지키면 개선\n· 식초 먼저·열: 잔색 가능",
        "· Đúng thứ tự: cải thiện\n· Giấm trước/nhiệt: dễ còn",
        ["식초를 효소·세제보다 먼저 쓰지 마세요"],
        ["Không giấm trước enzyme/xà phòng"],
    ),
]

EXTRA_STATUS_KO: dict[str, str] = {}
EXTRA_STATUS_VI: dict[str, str] = {}
EXTRA_TOOL_EXTRAS: dict[str, dict[str, list[str]]] = {}
EXTRA_SOFT_OUTLOOK: dict[str, dict[str, str]] = {}
EXTRA_DONTS_KO: dict[str, list[str]] = {}
EXTRA_DONTS_VI: dict[str, list[str]] = {}

for (
    sid,
    sk,
    sv,
    tk,
    tv,
    ok,
    ov,
    dk,
    dv,
) in _ROWS:
    EXTRA_STATUS_KO[sid] = f"◆ 【먼저 확인】 {sk}"
    EXTRA_STATUS_VI[sid] = f"◆ 【Kiểm tra trước】 {sv}"
    EXTRA_TOOL_EXTRAS[sid] = {"ko": tk, "vi": tv, "en": tk}
    EXTRA_SOFT_OUTLOOK[sid] = _out(ok, ov)
    EXTRA_DONTS_KO[sid] = dk
    EXTRA_DONTS_VI[sid] = dv
